name: test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    FOUNDRY_PROFILE: ci

jobs:
    check:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "Install Foundry"
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: "Install Bun"
              uses: "oven-sh/setup-bun@v1"

            - name: "Install the Node.js dependencies"
              run: "bun install --frozen-lockfile"

            - name: "Run Forge build"
              run: |
                  forge --version
                  forge build
              id: build

            - name: "Run Forge tests"
              run: |
                  forge test -vvv
              id: test
