name: test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    FOUNDRY_PROFILE: ci

jobs:
    check:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "Install Foundry"
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: "Install Bun"
              uses: "oven-sh/setup-bun@v1"

            - name: "Install the Node.js dependencies"
              run: "bun install --frozen-lockfile"

            - name: "Build the contracts"
              run: "FOUNDRY_PROFILE=optimized forge build"
              id: build

            - name: "Run the tests"
              run: "FOUNDRY_PROFILE=optimized forge test -vvv"
              id: test
